### ISSUE TITLE
Adjust prediction (top-n)

### ISSUE THREAD

**Issue by lmaraite** [leonm13/Collaborative_Filtering#8]
A movie with a predicted rating of 5 and a nearest neighborhood of length 1 is getting higher ranked in the top-n list than a movie with a rating of 4.8 and a nearest neighborhood of 10 which is much more accurate. Fix this...

**Comment by cvonder1** [comment]
Good point, feels a bit odd to me too. How would you weight those predictions, to accomplish this?

On page 39 in "Recommender Systems: The Textbook", the "impact of the long tail" is described. Do you mean that? He uses the inverse user frequency, to get rid of the problem.
But that inverse user frequency is used in the similarity computation and not in the top-n list, so that might just be another separate issue, to think about.

**Comment by lmaraite** [comment]
I'm actually talking about data sparsity. There are items where we just can calculate a similarity to three other items. And two of these similarities are negative. So we actually only take one similarity into account. So a prediction based on a similarity to one other item will not be as accurate as a prediction based on a similarity to ten other items.
I'm searching for scientific articles which handle this. If I can't find a good solution I will probably just say if a item does not have a minimum of k-nearest neighbors, it will not appear in a top-n list of recommendations.
